name: Build and Upload Bottles

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-bot:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install dependencies
        run: |
          brew install git

      - name: Run brew test-bot
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          mkdir -p /Users/runner/work/brew-test-bot
          export GITHUB_WORKSPACE=/Users/runner/work/brew-test-bot
          export HOMEBREW_CACHE=${GITHUB_WORKSPACE}/cache
          brew test-bot --only-formulae --root-url="https://github.com/draftbrew/homebrew-tap/releases/download/"

      - name: Upload Bottles
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bottles
          path: '*.tar.gz'
